backend:
  name: github
  repo: anandkumarjha11110/geopolis-site
  branch: main
  base_url: https://geopolis-oauth.anandkumarjha11110.workers.dev
  site_domain: geopolis-site.anandkumarjha11110.workers.dev

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["Geopolitics", "IR", "Policy", "Opinion"] }
      - { label: "Body", name: "body", widget: "markdown" }
